var Thrift={Version:"1.0.0-dev",Type:{STOP:0,VOID:1,BOOL:2,BYTE:3,I08:3,DOUBLE:4,I16:6,I32:8,I64:10,STRING:11,UTF7:11,STRUCT:12,MAP:13,SET:14,LIST:15,UTF8:16,UTF16:17},MessageType:{CALL:1,REPLY:2,EXCEPTION:3,ONEWAY:4},objectLength:function(a){var b=0,c;for(c in a)a.hasOwnProperty(c)&&b++;return b},inherits:function(a,b,c){function d(){}d.prototype=b.prototype;a.prototype=new d;a.prototype.name=c||""},TException:function(a){this.message=a}};Thrift.inherits(Thrift.TException,Error,"TException");
Thrift.TException.prototype.getMessage=function(){return this.message};Thrift.TApplicationExceptionType={UNKNOWN:0,UNKNOWN_METHOD:1,INVALID_MESSAGE_TYPE:2,WRONG_METHOD_NAME:3,BAD_SEQUENCE_ID:4,MISSING_RESULT:5,INTERNAL_ERROR:6,PROTOCOL_ERROR:7,INVALID_TRANSFORM:8,INVALID_PROTOCOL:9,UNSUPPORTED_CLIENT_TYPE:10};Thrift.TApplicationException=function(a,b){this.message=a;this.code="number"===typeof b?b:0};Thrift.inherits(Thrift.TApplicationException,Thrift.TException,"TApplicationException");
Thrift.TApplicationException.prototype.read=function(a){for(;;){var b=a.readFieldBegin();if(b.ftype==Thrift.Type.STOP)break;switch(b.fid){case 1:b.ftype==Thrift.Type.STRING?(b=a.readString(),this.message=b.value):a.skip(b.ftype);break;case 2:b.ftype==Thrift.Type.I32?(b=a.readI32(),this.code=b.value):a.skip(b.ftype);break;default:a.skip(b.ftype)}a.readFieldEnd()}a.readStructEnd()};
Thrift.TApplicationException.prototype.write=function(a){a.writeStructBegin("TApplicationException");this.message&&(a.writeFieldBegin("message",Thrift.Type.STRING,1),a.writeString(this.getMessage()),a.writeFieldEnd());this.code&&(a.writeFieldBegin("type",Thrift.Type.I32,2),a.writeI32(this.code),a.writeFieldEnd());a.writeFieldStop();a.writeStructEnd()};Thrift.TApplicationException.prototype.getCode=function(){return this.code};
Thrift.Transport=Thrift.TXHRTransport=function(a,b){this.url=a;this.rpos=this.wpos=0;this.useCORS=b&&b.useCORS;this.recv_buf=this.send_buf=""};
Thrift.TXHRTransport.prototype={getXmlHttpRequestObject:function(){try{return new XMLHttpRequest}catch(a){}try{return new ActiveXObject("Msxml2.XMLHTTP")}catch(b){}try{return new ActiveXObject("Microsoft.XMLHTTP")}catch(c){}throw"Your browser doesn't support XHR.";},flush:function(a,b){var c=this;if(a&&!b||void 0===this.url||""===this.url)return this.send_buf;var d=this.getXmlHttpRequestObject();d.overrideMimeType&&d.overrideMimeType("application/vnd.apache.thrift.json; charset=utf-8");b&&(d.onreadystatechange=
function(){return function(){4==this.readyState&&200==this.status&&(c.setRecvBuffer(this.responseText),b())}}());d.open("POST",this.url,!!a);d.setRequestHeader&&(d.setRequestHeader("Accept","application/vnd.apache.thrift.json; charset=utf-8"),d.setRequestHeader("Content-Type","application/vnd.apache.thrift.json; charset=utf-8"));d.send(this.send_buf);if(!a||!b){if(4!=d.readyState)throw"encountered an unknown ajax ready state: "+d.readyState;if(200!=d.status)throw"encountered a unknown request status: "+
d.status;this.recv_buf=d.responseText;this.wpos=this.recv_buf_sz=this.recv_buf.length;this.rpos=0}},jqRequest:function(a,b,c,d){if("undefined"===typeof jQuery||"undefined"===typeof jQuery.Deferred)throw"Thrift.js requires jQuery 1.5+ to use asynchronous requests";var e=this;return jQuery.ajax({url:this.url,data:b,type:"POST",cache:!1,contentType:"application/vnd.apache.thrift.json; charset=utf-8",dataType:"text thrift",converters:{"text thrift":function(b){e.setRecvBuffer(b);return d.call(a)}},context:a,
success:jQuery.makeArray(c).pop()})},setRecvBuffer:function(a){this.recv_buf=a;this.wpos=this.recv_buf_sz=this.recv_buf.length;this.rpos=0},isOpen:function(){return!0},open:function(){},close:function(){},read:function(a){var b=this.wpos-this.rpos;if(0===b)return"";var c=a;b<a&&(c=b);a=this.read_buf.substr(this.rpos,c);this.rpos+=c;return a},readAll:function(){return this.recv_buf},write:function(a){this.send_buf=a},getSendBuffer:function(){return this.send_buf}};Thrift.TWebSocketTransport=function(a){this.__reset(a)};
Thrift.TWebSocketTransport.prototype={__reset:function(a){this.url=a;this.socket=null;this.callbacks=[];this.send_pending=[];this.recv_buf=this.send_buf="";this.rb_rpos=this.rb_wpos=0},flush:function(a,b){var c=this;this.isOpen()?(this.socket.send(this.send_buf),this.callbacks.push(function(){return function(a){c.setRecvBuffer(a);b()}}())):this.send_pending.push({buf:this.send_buf,cb:b})},__onOpen:function(){var a=this;0<this.send_pending.length&&(this.send_pending.forEach(function(b){this.socket.send(b.buf);
this.callbacks.push(function(){var c=b.cb;return function(b){a.setRecvBuffer(b);c()}}())}),this.send_pending=[])},__onClose:function(a){this.__reset(this.url)},__onMessage:function(a){this.callbacks.length&&this.callbacks.shift()(a.data)},__onError:function(a){console.log("Thrift WebSocket Error: "+a.toString());this.socket.close()},setRecvBuffer:function(a){this.recv_buf=a;this.wpos=this.recv_buf_sz=this.recv_buf.length;this.rpos=0},isOpen:function(){return this.socket&&this.socket.readyState==this.socket.OPEN},
open:function(){this.socket&&this.socket.readyState!=this.socket.CLOSED||(this.socket=new WebSocket(this.url),this.socket.onopen=this.__onOpen.bind(this),this.socket.onmessage=this.__onMessage.bind(this),this.socket.onerror=this.__onError.bind(this),this.socket.onclose=this.__onClose.bind(this))},close:function(){this.socket.close()},read:function(a){var b=this.wpos-this.rpos;if(0===b)return"";var c=a;b<a&&(c=b);a=this.read_buf.substr(this.rpos,c);this.rpos+=c;return a},readAll:function(){return this.recv_buf},
write:function(a){this.send_buf=a},getSendBuffer:function(){return this.send_buf}};Thrift.TJSONProtocol=Thrift.Protocol=function(a){this.tstack=[];this.tpos=[];this.transport=a};Thrift.Protocol.Type={};Thrift.Protocol.Type[Thrift.Type.BOOL]='"tf"';Thrift.Protocol.Type[Thrift.Type.BYTE]='"i8"';Thrift.Protocol.Type[Thrift.Type.I16]='"i16"';Thrift.Protocol.Type[Thrift.Type.I32]='"i32"';Thrift.Protocol.Type[Thrift.Type.I64]='"i64"';Thrift.Protocol.Type[Thrift.Type.DOUBLE]='"dbl"';
Thrift.Protocol.Type[Thrift.Type.STRUCT]='"rec"';Thrift.Protocol.Type[Thrift.Type.STRING]='"str"';Thrift.Protocol.Type[Thrift.Type.MAP]='"map"';Thrift.Protocol.Type[Thrift.Type.LIST]='"lst"';Thrift.Protocol.Type[Thrift.Type.SET]='"set"';Thrift.Protocol.RType={};Thrift.Protocol.RType.tf=Thrift.Type.BOOL;Thrift.Protocol.RType.i8=Thrift.Type.BYTE;Thrift.Protocol.RType.i16=Thrift.Type.I16;Thrift.Protocol.RType.i32=Thrift.Type.I32;Thrift.Protocol.RType.i64=Thrift.Type.I64;Thrift.Protocol.RType.dbl=Thrift.Type.DOUBLE;
Thrift.Protocol.RType.rec=Thrift.Type.STRUCT;Thrift.Protocol.RType.str=Thrift.Type.STRING;Thrift.Protocol.RType.map=Thrift.Type.MAP;Thrift.Protocol.RType.lst=Thrift.Type.LIST;Thrift.Protocol.RType.set=Thrift.Type.SET;Thrift.Protocol.Version=1;
Thrift.Protocol.prototype={getTransport:function(){return this.transport},writeMessageBegin:function(a,b,c){this.tstack=[];this.tpos=[];this.tstack.push([Thrift.Protocol.Version,'"'+a+'"',b,c])},writeMessageEnd:function(){var a=this.tstack.pop();this.wobj=this.tstack.pop();this.wobj.push(a);this.wbuf="["+this.wobj.join(",")+"]";this.transport.write(this.wbuf)},writeStructBegin:function(a){this.tpos.push(this.tstack.length);this.tstack.push({})},writeStructEnd:function(){var a=this.tpos.pop(),b=this.tstack[a],
c="{",d=!0,e;for(e in b)d?d=!1:c+=",",c+=e+":"+b[e];this.tstack[a]=c+"}"},writeFieldBegin:function(a,b,c){this.tpos.push(this.tstack.length);this.tstack.push({fieldId:'"'+c+'"',fieldType:Thrift.Protocol.Type[b]})},writeFieldEnd:function(){var a=this.tstack.pop(),b=this.tstack.pop();this.tstack[this.tstack.length-1][b.fieldId]="{"+b.fieldType+":"+a+"}";this.tpos.pop()},writeFieldStop:function(){},writeMapBegin:function(a,b,c){this.tpos.push(this.tstack.length);this.tstack.push([Thrift.Protocol.Type[a],
Thrift.Protocol.Type[b],0])},writeMapEnd:function(){var a=this.tpos.pop();if(a!=this.tstack.length){0!==(this.tstack.length-a-1)%2&&this.tstack.push("");this.tstack[a][this.tstack[a].length-1]=(this.tstack.length-a-1)/2;for(var b="}",c=!0;this.tstack.length>a+1;){var d=this.tstack.pop(),e=this.tstack.pop();c?c=!1:b=","+b;isNaN(e)||(e='"'+e+'"');b=e+":"+d+b}this.tstack[a].push("{"+b);this.tstack[a]="["+this.tstack[a].join(",")+"]"}},writeListBegin:function(a,b){this.tpos.push(this.tstack.length);this.tstack.push([Thrift.Protocol.Type[a],
b])},writeListEnd:function(){for(var a=this.tpos.pop();this.tstack.length>a+1;){var b=this.tstack[a+1];this.tstack.splice(a+1,1);this.tstack[a].push(b)}this.tstack[a]="["+this.tstack[a].join(",")+"]"},writeSetBegin:function(a,b){this.tpos.push(this.tstack.length);this.tstack.push([Thrift.Protocol.Type[a],b])},writeSetEnd:function(){for(var a=this.tpos.pop();this.tstack.length>a+1;){var b=this.tstack[a+1];this.tstack.splice(a+1,1);this.tstack[a].push(b)}this.tstack[a]="["+this.tstack[a].join(",")+
"]"},writeBool:function(a){this.tstack.push(a?1:0)},writeByte:function(a){this.tstack.push(a)},writeI16:function(a){this.tstack.push(a)},writeI32:function(a){this.tstack.push(a)},writeI64:function(a){this.tstack.push(a)},writeDouble:function(a){this.tstack.push(a)},writeString:function(a){if(null===a)this.tstack.push(null);else{for(var b="",c=0;c<a.length;c++)var d=a.charAt(c),b='"'===d?b+'\\"':"\\"===d?b+"\\\\":"\b"===d?b+"\\b":"\f"===d?b+"\\f":"\n"===d?b+"\\n":"\r"===d?b+"\\r":"\t"===d?b+"\\t":
b+d;this.tstack.push('"'+b+'"')}},writeBinary:function(a){this.writeString(a)},readMessageBegin:function(){this.rstack=[];this.rpos=[];this.robj="undefined"!==typeof JSON&&"function"===typeof JSON.parse?JSON.parse(this.transport.readAll()):"undefined"!==typeof jQuery?jQuery.parseJSON(this.transport.readAll()):eval(this.transport.readAll());var a={},b=this.robj.shift();if(b!=Thrift.Protocol.Version)throw"Wrong thrift protocol version: "+b;a.fname=this.robj.shift();a.mtype=this.robj.shift();a.rseqid=
this.robj.shift();this.rstack.push(this.robj.shift());return a},readMessageEnd:function(){},readStructBegin:function(a){this.rstack[this.rstack.length-1]instanceof Array&&this.rstack.push(this.rstack[this.rstack.length-1].shift());return{fname:""}},readStructEnd:function(){this.rstack[this.rstack.length-2]instanceof Array&&this.rstack.pop()},readFieldBegin:function(){var a={},b=-1,c=Thrift.Type.STOP,d;for(d in this.rstack[this.rstack.length-1])if(null!==d){b=parseInt(d,10);this.rpos.push(this.rstack.length);
d=this.rstack[this.rstack.length-1][b];delete this.rstack[this.rstack.length-1][b];this.rstack.push(d);break}if(-1!=b)for(var e in this.rstack[this.rstack.length-1])null!==Thrift.Protocol.RType[e]&&(c=Thrift.Protocol.RType[e],this.rstack[this.rstack.length-1]=this.rstack[this.rstack.length-1][e]);a.fname="";a.ftype=c;a.fid=b;return a},readFieldEnd:function(){for(var a=this.rpos.pop();this.rstack.length>a;)this.rstack.pop()},readMapBegin:function(){var a=this.rstack.pop(),b=a.shift();b instanceof Array&&
(this.rstack.push(a),a=b,b=a.shift());var c={};c.ktype=Thrift.Protocol.RType[b];c.vtype=Thrift.Protocol.RType[a.shift()];c.size=a.shift();this.rpos.push(this.rstack.length);this.rstack.push(a.shift());return c},readMapEnd:function(){this.readFieldEnd()},readListBegin:function(){var a=this.rstack[this.rstack.length-1],b={};b.etype=Thrift.Protocol.RType[a.shift()];b.size=a.shift();this.rpos.push(this.rstack.length);this.rstack.push(a.shift());return b},readListEnd:function(){this.readFieldEnd()},readSetBegin:function(a,
b){return this.readListBegin(a,b)},readSetEnd:function(){return this.readListEnd()},readBool:function(){var a=this.readI32();a.value=null!==a&&"1"==a.value?!0:!1;return a},readByte:function(){return this.readI32()},readI16:function(){return this.readI32()},readI32:function(a){void 0===a&&(a=this.rstack[this.rstack.length-1]);var b={};if(a instanceof Array)b.value=0===a.length?void 0:a.shift();else if(a instanceof Object)for(var c in a){if(null!==c){this.rstack.push(a[c]);delete a[c];b.value=c;break}}else b.value=
a,this.rstack.pop();return b},readI64:function(){return this.readI32()},readDouble:function(){return this.readI32()},readString:function(){return this.readI32()},readBinary:function(){return this.readString()},skip:function(a){var b;switch(a){case Thrift.Type.STOP:return null;case Thrift.Type.BOOL:return this.readBool();case Thrift.Type.BYTE:return this.readByte();case Thrift.Type.I16:return this.readI16();case Thrift.Type.I32:return this.readI32();case Thrift.Type.I64:return this.readI64();case Thrift.Type.DOUBLE:return this.readDouble();
case Thrift.Type.STRING:return this.readString();case Thrift.Type.STRUCT:for(this.readStructBegin();;){a=this.readFieldBegin();if(a.ftype==Thrift.Type.STOP)break;this.skip(a.ftype);this.readFieldEnd()}this.readStructEnd();return null;case Thrift.Type.MAP:a=this.readMapBegin();for(b=0;b<a.size;b++)0<b&&this.rstack.length>this.rpos[this.rpos.length-1]+1&&this.rstack.pop(),this.skip(a.ktype),this.skip(a.vtype);this.readMapEnd();return null;case Thrift.Type.SET:a=this.readSetBegin();for(b=0;b<a.size;b++)this.skip(a.etype);
this.readSetEnd();return null;case Thrift.Type.LIST:a=this.readListBegin();for(b=0;b<a.size;b++)this.skip(a.etype);this.readListEnd();return null}}};Thrift.MultiplexProtocol=function(a,b,c,d){Thrift.Protocol.call(this,b,c,d);this.serviceName=a};Thrift.inherits(Thrift.MultiplexProtocol,Thrift.Protocol,"multiplexProtocol");
Thrift.MultiplexProtocol.prototype.writeMessageBegin=function(a,b,c){b===Thrift.MessageType.CALL||b===Thrift.MessageType.ONEWAY?Thrift.Protocol.prototype.writeMessageBegin.call(this,this.serviceName+":"+a,b,c):Thrift.Protocol.prototype.writeMessageBegin.call(this,a,b,c)};Thrift.Multiplexer=function(){this.seqid=0};
Thrift.Multiplexer.prototype.createClient=function(a,b,c){b.Client&&(b=b.Client);var d=this;b.prototype.new_seqid=function(){d.seqid+=1;return d.seqid};return new b(new Thrift.MultiplexProtocol(a,c))};var copyList,copyMap;copyList=function(a,b){if(!a)return a;var c;c=void 0===b.shift?b:b[0];var d=a.length,e=[],f,g;for(f=0;f<d;f++)g=a[f],null===c?e.push(g):c===copyMap||c===copyList?e.push(c(g,b.slice(1))):e.push(new c(g));return e};
copyMap=function(a,b){if(!a)return a;var c;c=void 0===b.shift?b:b[0];var d={},e,f;for(f in a)a.hasOwnProperty(f)&&(e=a[f],d[f]=null===c?e:c===copyMap||c===copyList?c(e,b.slice(1)):new c(e));return d};Thrift.copyMap=copyMap;Thrift.copyList=copyList;
